# Generated by Django 5.0.4 on 2024-04-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_delete_news_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='headline',
            name='vector',
            field=models.TextField(null=True),
        ),
    ]
